import type { AccessRole } from "@react-intelligence/shared";
import { Activity, KeyRound } from "lucide-react";
import { useEffect, useState } from "react";
import { App } from "./App";
import { api, AUTH_EXPIRED_EVENT, clearDashboardToken, getDashboardToken, setDashboardToken } from "./lib/api";

export interface DashboardIdentity {
  actor: string;
  role: AccessRole;
  appIds: string[] | "all";
}

export function AuthGate() {
  const [identity, setIdentity] = useState<DashboardIdentity>();
  const [checking, setChecking] = useState(Boolean(getDashboardToken()));
  const [error, setError] = useState("");

  useEffect(() => {
    if (!getDashboardToken()) return;
    api.me().then(setIdentity).catch(() => {
      clearDashboardToken();
      setError("The access token is invalid or has been revoked.");
    }).finally(() => setChecking(false));
  }, []);

  useEffect(() => {
    const expired = () => { setIdentity(undefined); setError("Your session expired. Enter a valid access token to continue."); };
    window.addEventListener(AUTH_EXPIRED_EVENT, expired);
    return () => window.removeEventListener(AUTH_EXPIRED_EVENT, expired);
  }, []);

  if (checking) return <div className="flex min-h-screen items-center justify-center bg-ink text-sm text-muted">Verifying access…</div>;
  if (identity) return <App identity={identity} onSignOut={() => { clearDashboardToken(); setIdentity(undefined); }} />;
  return <LoginPage error={error} onAuthenticated={setIdentity} />;
}

function LoginPage({ error, onAuthenticated }: { error: string; onAuthenticated: (identity: DashboardIdentity) => void }) {
  const [token, setToken] = useState("");
  const [message, setMessage] = useState(error);
  const [submitting, setSubmitting] = useState(false);

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    setSubmitting(true);
    setMessage("");
    try {
      setDashboardToken(token.trim());
      onAuthenticated(await api.me());
    } catch {
      clearDashboardToken();
      setMessage("The access token is invalid or has been revoked.");
    } finally {
      setSubmitting(false);
    }
  }

  return <main className="flex min-h-screen items-center justify-center bg-ink p-6 text-slate-100">
    <div className="w-full max-w-md rounded-xl border border-line bg-panel p-8 shadow-2xl">
      <div className="flex h-11 w-11 items-center justify-center rounded-lg bg-accent text-ink"><Activity size={22} /></div>
      <h1 className="mt-6 text-2xl font-semibold">React Intelligence</h1>
      <p className="mt-2 text-sm text-muted">Enter an owner, member, or viewer access token. It stays in this browser tab and is never compiled into the dashboard.</p>
      <form onSubmit={submit} className="mt-6 space-y-4">
        <label className="block text-sm"><span className="mb-2 block text-muted">Access token</span><div className="flex items-center gap-2 rounded-md border border-line bg-ink px-3"><KeyRound size={16} className="text-muted" /><input autoFocus type="password" autoComplete="current-password" value={token} onChange={(event) => setToken(event.target.value)} placeholder="ri_access_…" className="h-11 min-w-0 flex-1 bg-transparent outline-none" /></div></label>
        {message ? <p role="alert" className="text-sm text-bad">{message}</p> : null}
        <button disabled={!token.trim() || submitting} className="w-full rounded-md bg-accent px-4 py-2.5 text-sm font-semibold text-ink disabled:opacity-50">{submitting ? "Verifying…" : "Continue"}</button>
      </form>
      <p className="mt-5 text-xs text-muted">For a new self-hosted install, use the dashboard token generated by <code>pnpm setup</code>.</p>
    </div>
  </main>;
}
